### PR TITLE
Add boxes smhd, vmhd and dref

### PR DESCRIPTION
**Pull request by bbert**
These boxes are mandatory in a moov (see in sample test/fixtures/240fps_go_pro_hero_4.mp4)

### CODE REVIEW

**Comment by bbert** [comment]
Hi,
The Travis check does not pass, but it seems that the script does not build the library before running tests.
Dowe have to push also the build files in dist folder?

**Comment by tieleman** [comment]
I've only just gotten around to adding Travis, I've modified `npm test` to also run `grunt` to ensure we have an up-to-date build, so I think it should work now. I'll get back to this pull request by tomorrow I hope.

**Comment by bbert** [comment]
Hi,
For 'dref', I did this way to avoid adding one more file for parsing dref entries.
But if you prefer I can add a 'url,urn.js' file for parsing dref entries.

**Comment by tieleman** [comment]
Yes please, otherwise it also interferes with the ability to generate custom build files with only specific parsers.

**Pull request merged**
