### PR TITLE
Added support for mehd, mfro, stsd, tfra and trex atoms.

### PR DESCRIPTION
**Pull request by danotrilogic**
Hi,

I'm developing a streaming server using node.js and I found your library very useful, I added support for new boxes: Sample Description Box (with avc1 and aac info), Movie Fragment Random Access Box, Track Fragment Random Access Box, Movie Extends Header Box and Track Extends Box. 

I Hope this will be helpful for someone.
Regards,
David.

### CODE REVIEW

**Comment by tieleman** [comment]
Thanks David! Do you have a small MP4 fragment that contains these boxes? That way we can write tests against known content.

**Comment by danotrilogic** [comment]
Hi Sjoerd,

Thanks for the quick response, here you have a test file, it's a fragmented
MP4 that contains 2 tracks (audio and video), it also contains all the
related boxes (in red).

[ftyp] size=8+28
  major_brand = isom
  minor_version = 200
  compatible_brand = isom
  compatible_brand = iso2
  compatible_brand = avc1
  compatible_brand = mp41
  compatible_brand = iso5
[moov] size=8+1101
  [mvhd] size=12+96
    timescale = 1000
    duration = 2047
    duration(ms) = 2047
  [trak] size=8+477
    [tkhd] size=12+80, flags=7
      enabled = 1
      id = 1
      duration = 2000
      width = 320.000000
      height = 180.000000
    [mdia] size=8+377
      [mdhd] size=12+20
        timescale = 12288
        duration = 0
        duration(ms) = 0
        language = und
      [hdlr] size=12+41
        handler_type = vide
        handler_name = Bento4 Video Handler
      [minf] size=8+284
        [vmhd] size=12+8, flags=1
          graphics_mode = 0
          op_color = 0000,0000,0000
        [dinf] size=8+28
          [dref] size=12+16
            [url ] size=12+0, flags=1
              location = [local to file]
        [stbl] size=8+220
          [stsd] size=12+140
            entry-count = 1
            [avc1] size=8+128
              data_reference_index = 1
              width = 320
              height = 180
              compressor =
              [avcC] size=8+42
                Configuration Version = 1
                Profile = High
                Profile Compatibility = 0
                Level = 12
                NALU Length Size = 4
                Sequence Parameter = [67 64 00 0c ac d9 41 41 9f 9f 01 10
00 00 03 00 10 00 00 03 03 00 f1 42 99 60]
                Picture Parameter = [68 eb ec b2 2c]
          [stsz] size=12+8
            sample_size = 0
            sample_count = 0
          [stsc] size=12+4
            entry_count = 0
          [stts] size=12+4
            entry_count = 0
          [stco] size=12+4
            entry_count = 0
  [trak] size=8+412
    [tkhd] size=12+80, flags=7
      enabled = 1
      id = 2
      duration = 2047
      width = 0.000000
      height = 0.000000
    [mdia] size=8+312
      [mdhd] size=12+20
        timescale = 22000
        duration = 0
        duration(ms) = 0
        language = und
      [hdlr] size=12+41
        handler_type = soun
        handler_name = Bento4 Sound Handler
      [minf] size=8+219
        [smhd] size=12+4
          balance = 0
        [dinf] size=8+28
          [dref] size=12+16
            [url ] size=12+0, flags=1
              location = [local to file]
        [stbl] size=8+159
          [stsd] size=12+79
            entry-count = 1
            [mp4a] size=8+67
              data_reference_index = 1
              channel_count = 2
              sample_size = 16
              sample_rate = 22000
              [esds] size=12+27
                [ESDescriptor] size=2+25
                  es_id = 0
                  stream_priority = 0
                  [DecoderConfig] size=2+17
                    stream_type = 5
                    object_type = 64
                    up_stream = 0
                    buffer_size = 37500
                    max_bitrate = 300000
                    avg_bitrate = 30021
                    DecoderSpecificInfo = 13 90
                  [Descriptor:06] size=2+1
          [stsz] size=12+8
            sample_size = 0
            sample_count = 0
          [stsc] size=12+4
            entry_count = 0
          [stts] size=12+4
            entry_count = 0
          [stco] size=12+4
            entry_count = 0
  [mvex] size=8+80
    [mehd] size=12+4
      duration = 2047
    [trex] size=12+20
      track id = 1
      default sample description index = 1
      default sample duration = 0
      default sample size = 0
      default sample flags = 0
    [trex] size=12+20
      track id = 2
      default sample description index = 1
      default sample duration = 0
      default sample size = 0
      default sample flags = 0
[moof] size=8+664
  [mfhd] size=12+4
    sequence number = 1
  [traf] size=8+640
    [tfhd] size=12+8, flags=20020
      track ID = 1
      default sample flags = 1010000
    [tfdt] size=12+8, version=1
      base media decode time = 0
    [trun] size=12+588, flags=b05
      sample count = 48
      data offset = 680
      first sample flags = 2000000
[mdat] size=8+1665
[moof] size=8+424
  [mfhd] size=12+4
    sequence number = 2
  [traf] size=8+400
    [tfhd] size=12+4, flags=20000
      track ID = 2
    [tfdt] size=12+8, version=1
      base media decode time = 0
    [trun] size=12+352, flags=301
      sample count = 43
      data offset = 440
[mdat] size=8+7479
[moof] size=8+88
  [mfhd] size=12+4
    sequence number = 3
  [traf] size=8+64
    [tfhd] size=12+4, flags=20000
      track ID = 2
    [tfdt] size=12+8, version=1
      base media decode time = 44032
    [trun] size=12+16, flags=301
      sample count = 1
      data offset = 104
[mdat] size=8+201
[mfra] size=8+97
  [tfra] size=12+23
    track_ID = 1
    length_size_of_traf_num = 0
    length_size_of_trun_num = 0
    length_size_of_sample_num = 0
  [tfra] size=12+34
    track_ID = 2
    length_size_of_traf_num = 0
    length_size_of_trun_num = 0
    length_size_of_sample_num = 0
  [mfro] size=12+4
    mfra_size = 105

2016-03-22 10:18 GMT+01:00 Sjoerd Tieleman <notifications@github.com>:

**Comment by tieleman** [comment]
Thanks, but can you also attach the MP4 file itself to the issue? Or send it to me directly. I'd prefer a file to test against. See https://github.com/madebyhiro/codem-isoboxer/tree/master/test/fixtures for example test files, I write specs for these to make sure the parsers do what they say.

**Comment by danotrilogic** [comment]
Hi,

The file was attached in my last email, didn't you received it?

Regards

**Comment by tieleman** [comment]
No, I think Github strips the attachments when using e-mail to reply to issues. Can you upload it using the web interface, or either mail it directly to sjoerd@madebyhiro.com.

**Comment by tieleman** [comment]
Added for reference.
[test_frag.mp4.zip](https://github.com/madebyhiro/codem-isoboxer/files/185923/test_frag.mp4.zip)

**Comment by tieleman** [comment]
I've made a new version. Do note that I changed some bits: converted tabs to spaces and changed some of the attribute names to better match the spec. Also, the `stsd` implementation is still a bit incomplete. Hopefully at some point we'll have a full implementation.

**Comment by danotrilogic** [comment]
Hi Sjoerd,

Thanks for your work. Yes, stsd is incomplete, but I focused the
development in the most common codecs for MPEG-DASH, if we want to
implement all supported codecs that file will be very long, so maybe it
will need a refactor to have the codecs separated from the parser.

Regards,
David.


2016-03-29 14:46 GMT+02:00 Sjoerd Tieleman <notifications@github.com>:

**Pull request merged**
