### PR TITLE
Zero size / zero buffer issue

### PR DESCRIPTION
**Pull request by bendenoz**
Hi,

We recently came across an issue when garbage data is being fed to `ISOBox. _parseBox()`.

The behaviour is complete UI freeze, resulting in the browser or tab having to be closed and restarted. It happens when the buffer is made of zeroes, and size resolves to 0.
The DataView read does not account for the header size, resulting in an infinite loop at `ISOFile.parse()`

See PR for details / potential fix

Thanks,

### CODE REVIEW

**Comment by tieleman** [comment]
Thanks for the suggestion/fix. As all tests pass I assume we are in the clear, but there is one case (that we unfortunately currently don't have a test for) that might be a problem and that is that the spec says that if the size is 0, the box is expected to run until the end of the file. Would that case still work here? I'll see if I can find/generate a test case for this.

**Comment by bendenoz** [comment]
Hi. Thanks for your reply, yes I believe that case still works.
The problem with the current behaviour, is that it seeks to 8 bytes before the end of the file / buffer, and when the last 8 bytes are zeroes (as in our case), it will never exit the loop.

**Comment by tieleman** [comment]
Ok, if we run into any issues we'll add a correct test case at that point. Thanks.

**Comment by bendenoz** [comment]
Great, thanks!

**Pull request merged**
