### PR TITLE
Write functionnality

### PR DESCRIPTION
**Pull request by bbert**
Hi,
Big PR for adding writing functionnality. The objective is to enable:
- modifying a parsed file, i.e. modifying some fields values and/or adding some boxes
- creating an ISOFile and adding boxes
- and then writing the modified/created ISOFile into a buffer

Writing functionality may be required, for example for dash.js project in which we would like to be able to 'process' segments before pushing them to the browser's MSE buffers.

The objective is also to add these functionnalities without increasing too much the minified file size.

What has been done:
- mutualize read/parse and write operations in each box implementation. We have _boxProcessors instead of _boxParsers, and each box processor processes its field by using generic methods, for example:
    `this._procField('track_ID', 'uint', 32);`
- the fields processing methods use either the reading functions either the writing functions according to the operation type (`this._parsing`)
- add an output buffer to the box (`this._rawo`) that is used when writing the boxes. This buffer has to be different from the input buffer since we have to copy some data from input to output buffer for some fields that are stored as DataViews (for example mdat)
- store the box content for unknown boxes into `this._data` field to enable writing the box content
- add `create()`, `getLength()` and `write()` functions to ISOBox object. `getLength()` enables determining the output total size of the boxes before allocating buffer memoryand then writing boxes content.
- add `create()` and `write()` functions to ISOFile object.
- add `createFile()`, `createBox()` and `createFullBox()` methods to ISOBoxer's exported functions
- add the possibility to build the library with or without writing support.

Some tests have been added to test writing functionnality. The tests consists, for each provided sample file, in reading then writing the ISOFile and comparing the output buffer with the input file data.
This works except for 'spliced...' files that are not complete or corrupted (for example last 'ssix' box of spliced_10000.m4v has a declared size of 7998 but a real size of 337 bytes).

Regarding the minified file size:
- current version:  15972 bytes
- new version without writing functions: 16688 bytes (+4,48%)
- new version with writing functions: 21927 bytes (+37,28%)

Let me know if you have any question or concern.

### CODE REVIEW

**Comment by bbert** [comment]
I forgot to indicate I have put the box implementations in 'boxes' folder, and kept previous parsers implementations into 'parsers' folder. Thus you can compare the new implementation with the previous one. Finally, we should keep only 'boxes' folder.

**Comment by tieleman** [comment]
Thanks for the interesting pull request! Seems like a lot of nice work. I'll need some time to have a proper look at it if you don't mind. Hope to get around to it this week.

**Comment by tieleman** [comment]
Since all the tests pass I think we're good to go on this one. Can you remove the `parsers` directory? And I think (since we're always talking about `processors` now) a better name for the `boxes` directory would be `processors`. Thanks for this work!

**Comment by bbert** [comment]
Done.

**Comment by bbert** [comment]
Hi,
I have just realized I missed one use case for writing functionnality. The use case concerns some box you would like to move from a parent to a different parent.
This use case is not covered in this version. I am working on it and will let you know when it is done.
If you agree it's better to fix it in this PR.

**Comment by bbert** [comment]
Now, there are 2 ways of creating and appending boxes:

    var box = ISOBoxer.create(Full)Box(<type>, parent, <pos>);

or

    var box = ISOBoxer.create(Full)Box(<type>);
    parent.append(box, <pos>);

Use case when the new box being appended has been created when parsing another file:

    var isoFile = ISOBoxer.parseBuffer(<buffer>);
    var box2 = isoFile.fetch(<type>);
    parent.append(box2);

**Pull request merged**
