### PR TITLE
_readData

### PR DESCRIPTION
**Pull request by bbert**
Add ISOBox._readData() function to read any unparsed part of data within a box (for example for mdat box)

### CODE REVIEW

**Comment by tieleman** [comment]
Hi @bbert, can you explain a bit what the benefits/use-case for such a function would be? It seems redundant just to add this for `mdat` boxes and specifying a different size could put the cursor in a weird position that breaks additional parsing.

**Comment by bbert** [comment]
The benefit would be to have a common function to read some part of data without parsing any specific field, and this could be used also for other boxes than mdat. I was thinking of avc1 or mp4a boxes for example to get the AVCConfigurationRecord or esds block of data. I will make some other pull requests for these boxes.

**Comment by tieleman** [comment]
Ok, can you add a relevant case to this pull request? And if you're adding/changing parsers, could you include tests as well?

**Comment by bbert** [comment]
I have updated avc1 and mp4a boxes parsing, and added some tests for these boxes

**Comment by tieleman** [comment]
I've merged this, unfortunately I don't have access to ISO/IEC 14496-15:2014, so I can't really verify the box definitions.

**Pull request merged**
